# basic
name:               "La vie est drôle"


# info
author:
  facebook:         none
  twitter:          dontsay_lazy
  github:           CuiH
  linkedin:         hao-cui-3ab90214b
  email:            hcui1995@gmail.com

copyright:
  year:             2019
  name:             CuiH

url: http://cuih.xyz


# navigation
nav:
  - name:           "about"
    url:            "/about"
  - name:           "archive"
    url:            "/archive"
  - name:           "tags"
    url:            "/tags"


# Sass
sass:
  sass_dir:         _sass
  style:            :compressed


# build
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
