title: STEP by STEP UP↑↑↑↑
email: hcui1995@gmail.com
description: Life is a struggle.
url: http://cuih.xyz
twitter_username: ""
github_username:  CuiH

markdown: kramdown
theme: minima
permalink: /:title
plugins:
  - jekyll-feed
exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
