# basic
name:               "Life is a Struggle"


# info
author:
  facebook:         none
  twitter:          dontsay_lazy
  github:           CuiH
  linkedin:         hao-cui-3ab90214b
  email:            hcui1995@gmail.com

copyright:
  year:             2017
  name:             CuiH

description: Life is a struggle.

url: http://cuih.xyz


# navigation
nav:
  - name:           "about"
    url:            "/about"
  - name:           "archive"
    url:            "/archive"
  - name:           "tags"
    url:            "/tags"
  - name:           "works"
    url:            "/works"
  - name:           "github"
    url:            "https://github.com/CuiH"
  - name:           "resume"
    url:            "http://resume.cuih.xyz"


# Sass
sass:
  sass_dir:         _sass
  style:            :compressed


# build
markdown: kramdown

# permalink: /:title

plugins:
  - jekyll-feed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
